#include <kernel/idt.h>
#include <kernel/exceptions.h>
#include <stdio.h>
#include <kernel/video.h>

// Vector 0 : #DE Divide Error
// Fired by: DIV or IDIV with a zero divisor, or when the quotient overflows.
// frame->rip: points to the DIV/IDIV instruction.
// error_code: not present (always 0).
static void de_handler(interrupt_frame_t* frame) {
    (void)frame;
    // test - division by zero clears screen
    video_clear();
}

// Vector 1 : #DB Debug
// Fired by: hardware breakpoints (DR0-DR3), single-step (RFLAGS.TF=1),
//           or data/I-O watchpoints.
// frame->rip: points to the instruction that would execute next.
// error_code: not present (always 0).
static void db_handler(interrupt_frame_t* frame) {
    (void)frame;
}

// Vector 2 : NMI Non-Maskable Interrupt
// Fired by: hardware signal on the NMI pin : typically memory parity errors,
//           ECC errors, or watchdog timers. Cannot be masked with CLI.
// frame->rip: points to whatever instruction was interrupted.
// error_code: not present (always 0).
static void nmi_handler(interrupt_frame_t* frame) {
    (void)frame;
}

// Vector 3 : #BP Breakpoint
// Fired by: the INT3 instruction (0xCC opcode), used by debuggers.
// frame->rip: points to the instruction AFTER the INT3.
// error_code: not present (always 0).
static void bp_handler(interrupt_frame_t* frame) {
    (void)frame;
}

// Vector 4 : #OF Overflow
// Fired by: the INTO instruction when RFLAGS.OF=1.
// Rarely used in modern code.
// frame->rip: points to the instruction AFTER INTO.
// error_code: not present (always 0).
static void of_handler(interrupt_frame_t* frame) {
    (void)frame;
}

// Vector 5 : #BR Bound Range Exceeded
// Fired by: the BOUND instruction when the array index is out of range.
// Rarely used in modern 64-bit code (BOUND is invalid in 64-bit mode).
// frame->rip: points to the BOUND instruction.
// error_code: not present (always 0).
static void br_handler(interrupt_frame_t* frame) {
    (void)frame;
}

// Vector 6 : #UD Invalid Opcode
// Fired by: an undefined/unrecognised opcode, or a valid instruction used
//           in an invalid context (e.g. LOCK on a non-lockable instruction).
//           Also fired by the UD2 instruction intentionally.
// frame->rip: points to the invalid instruction.
// error_code: not present (always 0).
static void ud_handler(interrupt_frame_t* frame) {
    (void)frame;
}

// Vector 7 : #NM Device Not Available
// Fired by: an x87/MMX/SSE instruction when CR0.TS=1 (task switched) or
//           CR0.EM=1 (FPU emulation). Used to lazily save/restore FPU state.
// frame->rip: points to the FPU/SSE instruction.
// error_code: not present (always 0).
static void nm_handler(interrupt_frame_t* frame) {
    (void)frame;
}

// Vector 8 : #DF Double Fault
// Fired by: an exception occurring while the CPU is already handling another
//           exception and cannot handle them serially.
// This is fatal : the system cannot safely continue.
// frame->rip: unreliable. The system is in an undefined state.
// error_code: always 0 (pushed by CPU but meaningless).
static void df_handler(interrupt_frame_t* frame) {
    (void)frame;
    for (;;) __asm__ volatile ("hlt");
}

// Vector 9 : Coprocessor Segment Overrun (legacy)
// Fired by: old x87 FPU segment boundary violations. Not generated by
//           modern CPUs. Safe to ignore.
// error_code: not present (always 0).
static void cso_handler(interrupt_frame_t* frame) {
    (void)frame;
}

// Vector 10 : #TS Invalid TSS
// Fired by: a task switch or inter-privilege call to a segment whose TSS
//           is invalid (bad limit, wrong type, not present).
// frame->rip: points to the instruction that caused the switch.
// error_code: selector index of the bad segment + table indicator bits.
static void ts_handler(interrupt_frame_t* frame) {
    (void)frame;
}

// Vector 11 : #NP Segment Not Present
// Fired by: loading a segment register with a descriptor that has P=0
//           (present bit clear).
// frame->rip: points to the instruction that loaded the segment.
// error_code: selector index of the not-present segment + table bits.
static void np_handler(interrupt_frame_t* frame) {
    (void)frame;
}

// Vector 12 : #SS Stack Segment Fault
// Fired by: accessing the stack beyond its limit, or loading SS with a
//           not-present descriptor.
// frame->rip: points to the faulting instruction.
// error_code: selector index (or 0 if caused by a stack limit violation).
static void ss_handler(interrupt_frame_t* frame) {
    (void)frame;
}

// Vector 13 : #GP General Protection Fault
// Fired by: almost everything illegal : segment limit violation, privilege
//           violation, reserved bit set, executing a privileged instruction
//           from ring 3, writing to a read-only page (if not #PF), etc.
//           The most common exception you will see during kernel development.
// frame->rip: points to the faulting instruction.
// error_code: segment selector index if the fault is segment-related, 0 otherwise.
static void gp_handler(interrupt_frame_t* frame) {
    (void)frame;
}

// Vector 14 : #PF Page Fault
// Fired by: any memory access to a page that is not present, not writable,
//           not executable (NX), or involves a privilege violation.
// frame->rip: points to the instruction that caused the fault.
// error_code bits:
//   bit 0 (P)  : 0 = page not present, 1 = protection violation
//   bit 1 (W)  : 0 = read, 1 = write
//   bit 2 (U)  : 0 = kernel access, 1 = user access
//   bit 3 (R)  : 1 = reserved bit set in page table entry
//   bit 4 (I)  : 1 = instruction fetch (NX violation)
// CR2 register holds the virtual address that caused the fault:
//   uint64_t fault_addr;
//   __asm__ volatile ("mov %%cr2, %0" : "=r"(fault_addr));
static void pf_handler(interrupt_frame_t* frame) {
    (void)frame;
}

// Vector 15 : Reserved
// Never fired by the CPU. Ignored.
static void reserved_handler(interrupt_frame_t* frame) {
    (void)frame;
}

// Vector 16 : #MF x87 FPU Floating-Point Error
// Fired by: a pending x87 FPU exception when the next x87 instruction
//           executes (deferred/precise model). Check the x87 status word.
// frame->rip: points to the x87 instruction that triggered the pending error.
// error_code: not present (always 0).
static void mf_handler(interrupt_frame_t* frame) {
    (void)frame;
}

// Vector 17 : #AC Alignment Check
// Fired by: a misaligned memory access when CPL=3 and CR0.AM=1 and RFLAGS.AC=1.
// Kernel code is not affected (CPL=0).
// frame->rip: points to the misaligned access instruction.
// error_code: always 0.
static void ac_handler(interrupt_frame_t* frame) {
    (void)frame;
}

// Vector 18 : #MC Machine Check
// Fired by: hardware errors detected by the CPU : cache ECC, bus errors,
//           TLB errors, etc. Model-specific; read MSRs for details.
// This is typically fatal. frame->rip and error_code are unreliable.
// error_code: not present (always 0).
static void mc_handler(interrupt_frame_t* frame) {
    (void)frame;
    for (;;) __asm__ volatile ("hlt");
}

// Vector 19 : #XM SIMD Floating-Point Exception
// Fired by: an unmasked SSE/SSE2/SSE3 floating-point exception
//           (divide by zero, overflow, underflow, precision, etc.).
//           Check the MXCSR register for the specific cause.
// frame->rip: points to the SSE instruction that raised the exception.
// error_code: not present (always 0).
static void xm_handler(interrupt_frame_t* frame) {
    (void)frame;
}

// Vector 20 : #VE Virtualization Exception
// Fired by: EPT (Extended Page Tables) violations when the "EPT-violation #VE"
//           VM-execution control is enabled. Only relevant inside a VMX guest.
// error_code: not present (always 0).
static void ve_handler(interrupt_frame_t* frame) {
    (void)frame;
}

// Vector 21 : #CP Control Protection Exception
// Fired by: a shadow stack violation (CET : Control-flow Enforcement Tech),
//           e.g. a RET that does not match the shadow stack, or an indirect
//           branch to an address without an ENDBR64 landing pad.
// frame->rip: points to the instruction that caused the violation.
// error_code: encodes which CET feature caused the fault.
static void cp_handler(interrupt_frame_t* frame) {
    (void)frame;
}

// Vectors 22-31 : Reserved
// Never fired by current CPUs. Registered to catch spurious entries.
static void reserved2_handler(interrupt_frame_t* frame) {
    (void)frame;
}

// Register Exceptions
void exceptions_init(void) {
    idt_register_handler(0,  de_handler);
    idt_register_handler(1,  db_handler);
    idt_register_handler(2,  nmi_handler);
    idt_register_handler(3,  bp_handler);
    idt_register_handler(4,  of_handler);
    idt_register_handler(5,  br_handler);
    idt_register_handler(6,  ud_handler);
    idt_register_handler(7,  nm_handler);
    idt_register_handler(8,  df_handler);
    idt_register_handler(9,  cso_handler);
    idt_register_handler(10, ts_handler);
    idt_register_handler(11, np_handler);
    idt_register_handler(12, ss_handler);
    idt_register_handler(13, gp_handler);
    idt_register_handler(14, pf_handler);
    idt_register_handler(15, reserved_handler);
    idt_register_handler(16, mf_handler);
    idt_register_handler(17, ac_handler);
    idt_register_handler(18, mc_handler);
    idt_register_handler(19, xm_handler);
    idt_register_handler(20, ve_handler);
    idt_register_handler(21, cp_handler);
    for (int i = 22; i <= 31; i++)
        idt_register_handler(i, reserved2_handler);

    
    printf("%s", "Registered exception handlers    [  ok  ]\n");
}